// Автоматически сгенерировано из data/products.xlsx. Не редактировать вручную.
// Запустите: npm run products

import type { Product } from "./types";

export const GENERATED_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Футболка Dior",
    brand: "Dior",
    price: 12000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773656982/tg-products/mkgmgaqkno4q4hasu2c8.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["бежевый"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-16T00:00:00.000Z",
  },
  {
    id: "2",
    name: "Футболка Dior",
    brand: "Dior",
    price: 12000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773656985/tg-products/f5dyt9fxewjlgymvpe3c.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["белый"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-16T00:00:00.000Z",
  },
  {
    id: "3",
    name: "Платье Dior",
    brand: "Dior",
    price: 30000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773656988/tg-products/nd2ndp0l7e13lpno5hpb.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["белый"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-16T00:00:00.000Z",
  },
  {
    id: "4",
    name: "Футболка Dior",
    brand: "Dior",
    price: 12000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657069/tg-products/bhgxysknyx1l2jk9u3rn.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657073/tg-products/kwpdv0osksg4zvrudyr0.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["розовый"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-16T00:00:00.000Z",
  },
  {
    id: "5",
    name: "Свитер Dior",
    brand: "Dior",
    price: 22000,
    currency: "₽",
    description: "Материал шерсть и кашемир",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657077/tg-products/fkonfeve2z2633bk84ot.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["синий"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-16T00:00:00.000Z",
  },
  {
    id: "6",
    name: "Футболка Valentino",
    brand: "Valentino",
    price: 12000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657079/tg-products/z6chjwosq1tsmqmouhm6.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657082/tg-products/pw2oxr6l74zinnsgk6w0.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657085/tg-products/tjrhi6r2xvl4ygdssfrd.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657088/tg-products/d7dqmbr96bs05rswdldf.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657095/tg-products/thgk4m3rmewg5utuvs7v.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["голбой"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-16T00:00:00.000Z",
  },
  {
    id: "7",
    name: "Кардиган Dior",
    brand: "Dior",
    price: 24000,
    currency: "₽",
    description: "Материал шерсть и кашемир",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657098/tg-products/rsyptz7fwqfelmxy6ydw.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657100/tg-products/m9mzf7z9totbgmrwy7ly.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657147/tg-products/xncdhbxhflitmubbgm9a.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["голубой"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-16T00:00:00.000Z",
  },
  {
    id: "8",
    name: "Кардиган Dior",
    brand: "Dior",
    price: 27000,
    currency: "₽",
    description: "Материал кашемир",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657152/tg-products/jdsaqx31zr7cjvimmbxg.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657154/tg-products/fnys55hvcsadqrlc19hf.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657157/tg-products/bxyru9eahuawsrqxoquo.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["белый"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-16T00:00:00.000Z",
  },
  {
    id: "9",
    name: "Футболка Louis Vuitton",
    brand: "",
    price: 14000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657159/tg-products/ucwhnnndkjvjj0rfgch7.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657161/tg-products/rxt1h8ofjx9eqvv2sqqz.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657164/tg-products/sswmebnlaxvoisvuawct.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["бежевый"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-16T00:00:00.000Z",
  },
  {
    id: "10",
    name: "Брюки Chanel",
    brand: "Chanel",
    price: 36000,
    currency: "₽",
    description: "Материал шелк и полиэстер",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657167/tg-products/j01zqhctwihp1juowjcy.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657170/tg-products/ev23h726ddf3tyt3rrae.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["белый"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-16T00:00:00.000Z",
  },
  {
    id: "11",
    name: "Рубашка Chanel",
    brand: "Chanel",
    price: 39000,
    currency: "₽",
    description: "Материал шелк",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657172/tg-products/wh9xzqswuvwgbmafmluz.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657174/tg-products/tze9yngyvqu8mnmasdvh.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657180/tg-products/m7pvci0iacztyp6pr3u7.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657182/tg-products/ommnvpvdo3yckyr5vbst.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657185/tg-products/bfsigfbw8ak8ka48onij.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657188/tg-products/l0gopq2c6musnlcfoz5z.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["белый"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-16T00:00:00.000Z",
  },
  {
    id: "12",
    name: "Топ Chanel",
    brand: "Chanel",
    price: 22000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657191/tg-products/ppvqbfgli5m1qmlkdpuw.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657194/tg-products/a9mwskgzuxgao8coydke.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657197/tg-products/iq1cgfpw5bqfqcwfzyjq.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657199/tg-products/oaexxi222us3u7dda6d0.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657202/tg-products/fvclhikjdln1hshxsis1.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657206/tg-products/soyqphkxylqiok1qp2ci.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657208/tg-products/bjdt7gfw682yhvobjcbh.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["белый"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-16T00:00:00.000Z",
  },
  {
    id: "13",
    name: "Футболка Celine",
    brand: "Celine",
    price: 12000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657211/tg-products/yfbejf19ousiedoa3ro8.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657213/tg-products/gdxmqamyyx5qlu7xkcjk.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["белый"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-16T00:00:00.000Z",
  },
  {
    id: "14",
    name: "Кардиган Dior",
    brand: "Dior",
    price: 27000,
    currency: "₽",
    description: "Материал кашемир",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657325/tg-products/lxnge5xudt6hxnblg5qt.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657328/tg-products/qs1va9md29sm0hkbimbu.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["белый"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-16T00:00:00.000Z",
  },
  {
    id: "15",
    name: "Топ Dior",
    brand: "Dior",
    price: 20000,
    currency: "₽",
    description: "Материал кашемир",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657330/tg-products/a5b9x9ksqrjahiqvzb2d.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657332/tg-products/iqzouoeual1vbxgmuiul.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["белый"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-16T00:00:00.000Z",
  },
  {
    id: "16",
    name: "Рубашка Prada",
    brand: "Prada",
    price: 22000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657391/tg-products/f7cgt4vtzhjaxiozxcle.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["синий"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-16T00:00:00.000Z",
  },
  {
    id: "17",
    name: "Блузка Chloe",
    brand: "Celine",
    price: 22000,
    currency: "₽",
    description: "Материал шелк",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657393/tg-products/jsaz5u3qrqttlngmnfgv.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657423/tg-products/godbajmqrjcjbz8prrlc.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657426/tg-products/kpizlbff8kyvcowsrsqj.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["бежевый"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-16T00:00:00.000Z",
  },
  {
    id: "18",
    name: "Брюки Chanel",
    brand: "Chanel",
    price: 36000,
    currency: "₽",
    description: "Материал шелк и полиэстер",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657428/tg-products/bouempg5bkozzmhbe2xg.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657430/tg-products/u2nmfiipteo7m94vp7vw.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["белый"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-16T00:00:00.000Z",
  },
  {
    id: "19",
    name: "Шорты Miumiu",
    brand: "Miumiu",
    price: 20000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657432/tg-products/tbxjqmyd3vyze1jgmkvv.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["синий"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-16T00:00:00.000Z",
  },
  {
    id: "20",
    name: "Лонгслив Miumiu",
    brand: "Miumiu",
    price: 12000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657434/tg-products/petjj0v2jgsvjhxu2t2y.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657436/tg-products/glwgfyzvoxrivzb8bvrc.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["синий"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-16T00:00:00.000Z",
  },
  {
    id: "21",
    name: "Cумка Bottega Veneta",
    brand: "Bottega Veneta",
    price: 52000,
    currency: "₽",
    description: "Материал кожа",
    category: "bags",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773816112/tg-products/pitfg5ru3uln0ddtof3r.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773816115/tg-products/lxtt0igpkxfq0wsizh7i.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773816337/tg-products/phyafi9uw9fmj6bc1ci7.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["зеленый"],
    sizes: ["25х19 см"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "22",
    name: "Ветровка YSL",
    brand: "YSL",
    price: 39000,
    currency: "₽",
    description: "Материал нейлон",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773816339/tg-products/fsfrtxbtdfo0s02zgsmd.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773816341/tg-products/jn9iloy9lyux1gyegmxx.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773816513/tg-products/pakoq54nopsn1hndpde9.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773816516/tg-products/ayxvxbmsubumkq11iab2.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["бежевый"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "23",
    name: "Поло Miumiu",
    brand: "Miumiu",
    price: 13000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773816519/tg-products/ohoa6wyjmwem3mpabu2y.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["синий"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "24",
    name: "Лонгслив Celine",
    brand: "Celine",
    price: 13000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773816630/tg-products/rzhuphpv934hsspwjcac.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773816632/tg-products/wcczjq0eafp70qnq7yxb.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773816635/tg-products/y8abqxdgeqradf9v8kn3.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773816898/tg-products/wc9dbqqabjssntstope5.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773816901/tg-products/nqgnpv4nhjbwiu7hjvtq.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["белый"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "25",
    name: "Поло Miumiu",
    brand: "Miumiu",
    price: 13000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773816903/tg-products/di8f3jkcpgga3r9qmcyb.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773817251/tg-products/i734pcf89hwihtvndvkd.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["зеленый"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "26",
    name: "Юбка Prada",
    brand: "Prada",
    price: 19000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773817254/tg-products/rizqedb0kzzpw8mad3b6.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773817256/tg-products/d1fiiqkepfx7wueogmvt.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773817313/tg-products/b7eg1yovz5ynm5blftej.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773817315/tg-products/vcl3bibo013ehsgxzfpm.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["синий"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "27",
    name: "Джинсы Brunello Cucinelli",
    brand: "Brunello Cucinelli",
    price: 18000,
    currency: "₽",
    description: "Материал Хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773817318/tg-products/ylgzcd8hw89ryxuy9wgb.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773817502/tg-products/yxbdwftwbt2nwhpdltis.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773817505/tg-products/dbfkikayeksfittpg3c3.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["розовый"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "28",
    name: "Рубашка Valentino",
    brand: "Valentino",
    price: 19000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773817508/tg-products/w1svjywfln1pih49hg8t.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773817642/tg-products/lmdkaqnxyh5f14hohww3.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["белый"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "29",
    name: "Майка Prada",
    brand: "Prada",
    price: 19000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773817645/tg-products/jnynyokfyhj3qsyx9xnj.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773817647/tg-products/bfrmyir175yqnr9ob40p.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["черный"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "30",
    name: "Рубашка Brunello Cucinelli",
    brand: "Brunello Cucinelli",
    price: 32000,
    currency: "₽",
    description: "Материал шелк",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773817754/tg-products/cpfreiffmhgyzd93datj.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773817756/tg-products/sf2k3vztxn4ic512gzsx.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773817758/tg-products/jh8oydbviq4dukpfcnu8.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773817777/tg-products/db51stpkjb9qyt1xf4oa.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773817780/tg-products/riy5n5zhqnbwt4pmjth6.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["бежевый"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "31",
    name: "Рубашка Brunello Cucinelli",
    brand: "Brunello Cucinelli",
    price: 28000,
    currency: "₽",
    description: "Материал шелк",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773817782/tg-products/ufiiywegloio1x0gqdup.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773830691/tg-products/dhjldil5xwzxwdvvsy4d.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["коричневый"],
    sizes: ["S", "M", "L"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "32",
    name: "Кроссовки Hermes",
    brand: "Hermes",
    price: 21000,
    currency: "₽",
    description: "Материал кожа",
    category: "shoes",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773830697/tg-products/t58uzuebmuahcobfnwve.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773830700/tg-products/rodsy5dk3l0a8xiqcril.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["черный"],
    sizes: ["35", "36", "37", "38", "39", "40"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "33",
    name: "Кроссовки Hermes",
    brand: "Hermes",
    price: 24000,
    currency: "₽",
    description: "Материал кожа",
    category: "shoes",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773830715/tg-products/quangmttkambhc1znxav.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["голубой"],
    sizes: ["35", "36", "37", "38", "39", "40", "41"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "34",
    name: "Кроссовки Hermes",
    brand: "Hermes",
    price: 24000,
    currency: "₽",
    description: "Материал кожа",
    category: "shoes",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773831036/tg-products/unwdetsib4dlzmfdv48s.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["бежевый"],
    sizes: ["35", "36", "37", "38", "39", "40", "41"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "35",
    name: "Кроссовки Hermes",
    brand: "Hermes",
    price: 24000,
    currency: "₽",
    description: "Материал кожа",
    category: "shoes",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773831046/tg-products/grimurzletjsua1gmqk1.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["желтый"],
    sizes: ["35", "36", "37", "38", "39", "40", "41"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "36",
    name: "Кроссовки Hermes",
    brand: "Hermes",
    price: 24000,
    currency: "₽",
    description: "Материал кожа",
    category: "shoes",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773831079/tg-products/jloj0hbjgwekrutieahz.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["зеленый"],
    sizes: ["35", "36", "37", "38", "39", "40", "41"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "37",
    name: "Кроссовки Hermes",
    brand: "Hermes",
    price: 24000,
    currency: "₽",
    description: "Материал кожа",
    category: "shoes",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773831089/tg-products/hxkhhhip0ijqt5v5q2mx.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["черный"],
    sizes: ["35", "36", "37", "38", "39", "40", "41"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "38",
    name: "Сандали Hermes",
    brand: "Hermes",
    price: 24000,
    currency: "₽",
    description: "Материал кожа",
    category: "shoes",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773832274/tg-products/g6hhw3jzcfj9zpmhubw4.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["розовый"],
    sizes: ["35", "36", "37", "38", "39", "40", "41"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "39",
    name: "Сандали Hermes",
    brand: "Hermes",
    price: 24000,
    currency: "₽",
    description: "Материал кожа",
    category: "shoes",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773832280/tg-products/feqhnyy71cywneo2dgpl.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["зеленый"],
    sizes: ["35", "36", "37", "38", "39", "40", "41"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "40",
    name: "Сандали Hermes",
    brand: "Hermes",
    price: 24000,
    currency: "₽",
    description: "Материал кожа",
    category: "shoes",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773832369/tg-products/aldnd72iz8d5gxonmpru.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["белый"],
    sizes: ["35", "36", "37", "38", "39", "40", "41"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "41",
    name: "Сандали Hermes",
    brand: "Hermes",
    price: 24000,
    currency: "₽",
    description: "Материал кожа",
    category: "shoes",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773832380/tg-products/nfwisjjlygrbiwvqrlnj.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["коричневый"],
    sizes: ["35", "36", "37", "38", "39", "40", "41"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "42",
    name: "Сандали Hermes",
    brand: "Hermes",
    price: 24000,
    currency: "₽",
    description: "Материал кожа",
    category: "shoes",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773832393/tg-products/tsrxehwaflauewsewans.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["коричневый"],
    sizes: ["35", "36", "37", "38", "39", "40", "41"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "43",
    name: "Сандали Hermes",
    brand: "Hermes",
    price: 24000,
    currency: "₽",
    description: "Материал кожа",
    category: "shoes",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773832415/tg-products/vqgvx5kif1xfzsda0sgk.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["коричневый"],
    sizes: ["35", "36", "37", "38", "39", "40", "41"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "44",
    name: "Сапоги Hermes",
    brand: "Hermes",
    price: 27000,
    currency: "₽",
    description: "Материал замша",
    category: "shoes",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773832469/tg-products/c3uwat07b6hj2gwxeieo.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["бежевый"],
    sizes: ["35", "36", "37", "38", "39", "40", "41"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "45",
    name: "Сапоги Hermes",
    brand: "Hermes",
    price: 27000,
    currency: "₽",
    description: "Материал кожа",
    category: "shoes",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773832489/tg-products/hoyxfa8ipfzqlzqak997.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["черный"],
    sizes: ["35", "36", "37", "38", "39", "40", "41"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "46",
    name: "Сандали Hermes",
    brand: "Hermes",
    price: 20000,
    currency: "₽",
    description: "Материал кожа",
    category: "shoes",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773832537/tg-products/t0e2rduxmfdir1orp8pj.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["белый"],
    sizes: ["35", "36", "37", "38", "39", "40", "41"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "47",
    name: "Сандали Hermes",
    brand: "Hermes",
    price: 20000,
    currency: "₽",
    description: "Материал кожа",
    category: "shoes",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773832550/tg-products/epnyi36al38fmhgtjvly.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["черный"],
    sizes: ["35", "36", "37", "38", "39", "40", "41"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "48",
    name: "Сандали Hermes",
    brand: "Hermes",
    price: 20000,
    currency: "₽",
    description: "Материал кожа",
    category: "shoes",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773832563/tg-products/ubk1xzznnsu2wdhbqxml.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["коричневый"],
    sizes: ["35", "36", "37", "38", "39", "40", "41"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "49",
    name: "Куртка Prada",
    brand: "Prada",
    price: 55000,
    currency: "₽",
    description: "Материал кожа",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773832870/tg-products/phxbyatfhjuwt6vmlvwo.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["черный"],
    sizes: ["S", "M", "L", "XL"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "50",
    name: "Куртка Miumiu",
    brand: "Miumiu",
    price: 55000,
    currency: "₽",
    description: "Материал кожа",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773832887/tg-products/ittb2gs68rdf0mj2jxli.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["черный"],
    sizes: ["S", "M", "L", "XL"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "51",
    name: "Куртка Miumiu",
    brand: "Miumiu",
    price: 55000,
    currency: "₽",
    description: "Материал кожа",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773832909/tg-products/xilvbbhlgzrhqzmi6aax.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["черный"],
    sizes: ["S", "M", "L", "XL"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "52",
    name: "Куртка Bottega Veneta",
    brand: "Bottega Veneta",
    price: 65000,
    currency: "₽",
    description: "Материал замша",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773832951/tg-products/oqyrr4f8dkvu1tbfp9pn.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["бежевый"],
    sizes: ["S", "M", "L", "XL"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "53",
    name: "Куртка Loewe",
    brand: "Loewe",
    price: 60000,
    currency: "₽",
    description: "Материал кожа",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773832970/tg-products/aeoeqtxt2jaikgzifwta.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["черный"],
    sizes: ["S", "M", "L", "XL"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "54",
    name: "Куртка Loewe",
    brand: "Loewe",
    price: 60000,
    currency: "₽",
    description: "Материал кожа",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773832980/tg-products/itzlzjtttic6kpfo9u6k.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["коричневый"],
    sizes: ["S", "M", "L", "XL"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "55",
    name: "Куртка Ralph Lauren",
    brand: "Ralph Lauren",
    price: 60000,
    currency: "₽",
    description: "Материал кожа",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773833016/tg-products/jeoxdlgvx885ilu5ppjy.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["коричневый"],
    sizes: ["S", "M", "L", "XL"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "56",
    name: "Куртка Bottega Veneta",
    brand: "Bottega Veneta",
    price: 55000,
    currency: "₽",
    description: "Материал кожа",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773833036/tg-products/fwfq56v1fhvye5vn7tca.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773833663/tg-products/dqdejnonpwlysoyuulm5.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773833667/tg-products/ajna4isso0n29hf2pece.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["коричневый"],
    sizes: ["S", "M", "L", "XL"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "57",
    name: "Сумка Bottega Veneta",
    brand: "Bottega Veneta",
    price: 64000,
    currency: "₽",
    description: "Материал замша",
    category: "bags",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773833670/tg-products/hwxadkpms9jh21fxw3jy.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773833745/tg-products/p55aadptaigq65lca5gw.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["бежевый"],
    sizes: ["39x25x18.5 см"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "58",
    name: "Сумка Bottega Veneta",
    brand: "Bottega Veneta",
    price: 64000,
    currency: "₽",
    description: "Материал кожа",
    category: "bags",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773833753/tg-products/n1h2jljzzvnvbb5vuqm9.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773833757/tg-products/hlit3tg9hcvolmikvqj8.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773833786/tg-products/itgmxlmrxnmqpluutqyg.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["зеленый"],
    sizes: ["39x25x18.5 см"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "59",
    name: "Сумка Bottega Veneta",
    brand: "Bottega Veneta",
    price: 64000,
    currency: "₽",
    description: "Материал кожа",
    category: "bags",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773833789/tg-products/hjhf0t97cpv5ikiaachr.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773833792/tg-products/i43cheic3jgchzlrutej.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["бордовый"],
    sizes: ["39x25x18.5 см"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "60",
    name: "Сумка Bottega Veneta",
    brand: "Bottega Veneta",
    price: 64000,
    currency: "₽",
    description: "Материал кожа",
    category: "bags",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773833835/tg-products/ybmj3n0lwzafivnpl1uw.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773833838/tg-products/js8z3k0d0dfxtckeecxz.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773833841/tg-products/ie7ieg44kpg7mqziwb5l.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["черный"],
    sizes: ["39x25x18.5 см"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "61",
    name: "Сумка Bottega Veneta",
    brand: "Bottega Veneta",
    price: 36000,
    currency: "₽",
    description: "Материал кожа",
    category: "bags",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773833909/tg-products/k4pbk87mhwndsrpoz0js.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773833913/tg-products/to7x83ks9mydmb4zwzfs.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773833917/tg-products/a0zubiodyon2xd1rfik2.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773833932/tg-products/fy8m8n6xt24oowu69bdl.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["красный"],
    sizes: ["21x11x9 см"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "62",
    name: "Сумка Bottega Veneta",
    brand: "Bottega Veneta",
    price: 36000,
    currency: "₽",
    description: "Материал кожа",
    category: "bags",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773833936/tg-products/kf5evug3y3afwlfsxe7k.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773833938/tg-products/uqpacz5ywnypbmulzpad.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["коричневый"],
    sizes: ["21x11x9 см"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "63",
    name: "Сумка Bottega Veneta",
    brand: "Bottega Veneta",
    price: 36000,
    currency: "₽",
    description: "Материал кожа",
    category: "bags",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773833962/tg-products/vxgzb3plkv0lljydi0ql.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773833965/tg-products/wsn7tqksvlrvoj5odctx.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773833969/tg-products/pboh9oo8jcgcnpj5bytv.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["зеленый"],
    sizes: ["21x11x9 см"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "64",
    name: "Сумка Bottega Veneta",
    brand: "Bottega Veneta",
    price: 36000,
    currency: "₽",
    description: "Материал кожа",
    category: "bags",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773834028/tg-products/dll5ilxr2cvrfrmb5zr6.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773834031/tg-products/tjayysex8bzeuofpthiq.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773834035/tg-products/isuda1chzxqhf49cazlb.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["коричневый"],
    sizes: ["21x11x9 см"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "65",
    name: "Сумка Bottega Veneta",
    brand: "Bottega Veneta",
    price: 36000,
    currency: "₽",
    description: "Материал кожа",
    category: "bags",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773834086/tg-products/q4zbjv25kvxpeiurtwb7.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773834089/tg-products/ah9ybpq58ps4c5cw1gsc.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773834092/tg-products/uy6cqzf4y0uro9otz8hf.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["черный"],
    sizes: ["21x11x9 см"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "66",
    name: "Кроссовки Hermes",
    brand: "Hermes",
    price: 21000,
    currency: "₽",
    description: "Материал кожа",
    category: "shoes",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773834321/tg-products/k4bkfhn2f10ssvrtgm5u.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["белый"],
    sizes: ["35", "36", "37", "38", "39", "40"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "67",
    name: "Кроссовки Hermes",
    brand: "Hermes",
    price: 21000,
    currency: "₽",
    description: "Материал кожа",
    category: "shoes",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773834325/tg-products/z3olimdqvrbbchauxyp8.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["белый"],
    sizes: ["35", "36", "37", "38", "39", "40"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "68",
    name: "Сумка Bottega Veneta",
    brand: "Bottega Veneta",
    price: 32000,
    currency: "₽",
    description: "Материал кожа",
    category: "bags",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773835308/tg-products/zyxgjrvtjv4ea5yd2whz.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773835311/tg-products/nj42wapveufuq94tux7b.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773835315/tg-products/ingo8tua2bmu4cjt7m9b.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773835498/tg-products/ixvsxn6ng5h39sv1jhkl.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773835503/tg-products/uyhrzy2a1xgzdlghyspy.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["голубой"],
    sizes: ["17x10x6 см"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "69",
    name: "Костюм Brunello Cucinelli",
    brand: "Brunello Cucinelli",
    price: 63000,
    currency: "₽",
    description: "Материал хлопок и лен",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773835510/tg-products/aebnsybv0vx8mlu8c3pq.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773835518/tg-products/yjwfs60rgbkm5sdc0mvj.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773835528/tg-products/kx4c8ffj2yggtj92tszv.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["коричневый"],
    sizes: ["S", "M", "L", "XL"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "70",
    name: "Куртка Brunello Cucinelli",
    brand: "Brunello Cucinelli",
    price: 36000,
    currency: "₽",
    description: "Материал хлопок и лен",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773835561/tg-products/djmln37ynprbvnw9j3kf.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773835567/tg-products/bcloy4laepu7xjnximux.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773835577/tg-products/ms4qzopjvfmnvxe4fyql.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773835610/tg-products/ry6zindmjsnornscgrre.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773835614/tg-products/maa475djsqbflpsu43uq.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773835617/tg-products/xfa7pbpame6l5jhjcy2r.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["бежевый"],
    sizes: ["S", "M", "L", "XL"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "71",
    name: "Куртка Brunello Cucinelli",
    brand: "Brunello Cucinelli",
    price: 36000,
    currency: "₽",
    description: "Материал шелк",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773835622/tg-products/xpswgt46xryxgyiizb5q.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773835759/tg-products/iwhcisnvkwzcfly0mlih.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773835767/tg-products/btetnlvzi7jaytlrij2j.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["бежевый"],
    sizes: ["S", "M", "L", "XL"],
    createdAt: "2026-03-17T21:00:00.000Z",
  },
  {
    id: "72",
    name: "Пиджак Loro Piana",
    brand: "Loro Piana",
    price: 25000,
    currency: "₽",
    description: "Материал шерсть",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773835773/tg-products/eokilkgoajhxjgjaknxs.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773835778/tg-products/auyz4azjhufbybxeoccy.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: ["бежевый"],
    sizes: ["S", "M", "L", "XL"],
    createdAt: "2026-03-17T21:00:00.000Z",
  }
];
