// Автоматически сгенерировано из data/products.xlsx. Не редактировать вручную.
// Запустите: npm run products

import type { Product } from "./types";

export const GENERATED_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Футболка Dior",
    brand: "Dior",
    price: 12000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773656982/tg-products/mkgmgaqkno4q4hasu2c8.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: [],
    sizes: ["S M L"],
    createdAt: "16.03.2026",
  },
  {
    id: "2",
    name: "Футболка Dior",
    brand: "Dior",
    price: 12000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773656985/tg-products/f5dyt9fxewjlgymvpe3c.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: [],
    sizes: ["S M L"],
    createdAt: "16.03.2026",
  },
  {
    id: "3",
    name: "Платье Dior",
    brand: "Dior",
    price: 30000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773656988/tg-products/nd2ndp0l7e13lpno5hpb.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: [],
    sizes: ["S M L"],
    createdAt: "16.03.2026",
  },
  {
    id: "4",
    name: "Футболка Dior",
    brand: "Dior",
    price: 12000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657069/tg-products/bhgxysknyx1l2jk9u3rn.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657073/tg-products/kwpdv0osksg4zvrudyr0.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: [],
    sizes: ["S M L"],
    createdAt: "16.03.2026",
  },
  {
    id: "5",
    name: "Свитер Dior",
    brand: "Dior",
    price: 22000,
    currency: "₽",
    description: "Материал шерсть и кашемир",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657077/tg-products/fkonfeve2z2633bk84ot.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: [],
    sizes: ["S M L"],
    createdAt: "16.03.2026",
  },
  {
    id: "6",
    name: "Футболка Valentino",
    brand: "Valentino",
    price: 12000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657079/tg-products/z6chjwosq1tsmqmouhm6.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657082/tg-products/pw2oxr6l74zinnsgk6w0.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657085/tg-products/tjrhi6r2xvl4ygdssfrd.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657088/tg-products/d7dqmbr96bs05rswdldf.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657095/tg-products/thgk4m3rmewg5utuvs7v.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: [],
    sizes: ["S M L"],
    createdAt: "16.03.2026",
  },
  {
    id: "7",
    name: "Кардиган Dior",
    brand: "Dior",
    price: 24000,
    currency: "₽",
    description: "Материал шерсть и кашемир",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657098/tg-products/rsyptz7fwqfelmxy6ydw.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657100/tg-products/m9mzf7z9totbgmrwy7ly.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657147/tg-products/xncdhbxhflitmubbgm9a.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: [],
    sizes: ["S M L"],
    createdAt: "16.03.2026",
  },
  {
    id: "8",
    name: "Кардиган Dior",
    brand: "Dior",
    price: 27000,
    currency: "₽",
    description: "Материал кашемир",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657152/tg-products/jdsaqx31zr7cjvimmbxg.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657154/tg-products/fnys55hvcsadqrlc19hf.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657157/tg-products/bxyru9eahuawsrqxoquo.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: [],
    sizes: ["S M L"],
    createdAt: "16.03.2026",
  },
  {
    id: "9",
    name: "Футболка Louis Vuitton",
    brand: "",
    price: 14000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657159/tg-products/ucwhnnndkjvjj0rfgch7.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657161/tg-products/rxt1h8ofjx9eqvv2sqqz.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657164/tg-products/sswmebnlaxvoisvuawct.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: [],
    sizes: ["S M L"],
    createdAt: "16.03.2026",
  },
  {
    id: "10",
    name: "Брюки Chanel",
    brand: "Chanel",
    price: 36000,
    currency: "₽",
    description: "Материал шелк и полиэстер",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657167/tg-products/j01zqhctwihp1juowjcy.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657170/tg-products/ev23h726ddf3tyt3rrae.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: [],
    sizes: ["S M L"],
    createdAt: "16.03.2026",
  },
  {
    id: "11",
    name: "Рубашка Chanel",
    brand: "Chanel",
    price: 39000,
    currency: "₽",
    description: "Материал шелк",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657172/tg-products/wh9xzqswuvwgbmafmluz.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657174/tg-products/tze9yngyvqu8mnmasdvh.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657180/tg-products/m7pvci0iacztyp6pr3u7.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657182/tg-products/ommnvpvdo3yckyr5vbst.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657185/tg-products/bfsigfbw8ak8ka48onij.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657188/tg-products/l0gopq2c6musnlcfoz5z.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: [],
    sizes: ["S M L"],
    createdAt: "16.03.2026",
  },
  {
    id: "12",
    name: "Топ Chanel",
    brand: "Chanel",
    price: 22000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657191/tg-products/ppvqbfgli5m1qmlkdpuw.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657194/tg-products/a9mwskgzuxgao8coydke.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657197/tg-products/iq1cgfpw5bqfqcwfzyjq.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657199/tg-products/oaexxi222us3u7dda6d0.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657202/tg-products/fvclhikjdln1hshxsis1.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657206/tg-products/soyqphkxylqiok1qp2ci.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657208/tg-products/bjdt7gfw682yhvobjcbh.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: [],
    sizes: ["S M L"],
    createdAt: "16.03.2026",
  },
  {
    id: "13",
    name: "Футболка Celine",
    brand: "Celine",
    price: 12000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657211/tg-products/yfbejf19ousiedoa3ro8.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657213/tg-products/gdxmqamyyx5qlu7xkcjk.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: [],
    sizes: ["S M L"],
    createdAt: "16.03.2026",
  },
  {
    id: "14",
    name: "Кардиган Dior",
    brand: "Dior",
    price: 27000,
    currency: "₽",
    description: "Материал кашемир",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657325/tg-products/lxnge5xudt6hxnblg5qt.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657328/tg-products/qs1va9md29sm0hkbimbu.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: [],
    sizes: ["S M L"],
    createdAt: "16.03.2026",
  },
  {
    id: "15",
    name: "Топ Dior",
    brand: "Dior",
    price: 20000,
    currency: "₽",
    description: "Материал кашемир",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657330/tg-products/a5b9x9ksqrjahiqvzb2d.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657332/tg-products/iqzouoeual1vbxgmuiul.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: [],
    sizes: ["S M L"],
    createdAt: "16.03.2026",
  },
  {
    id: "16",
    name: "Рубашка Prada",
    brand: "Prada",
    price: 22000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657391/tg-products/f7cgt4vtzhjaxiozxcle.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: [],
    sizes: ["S M L"],
    createdAt: "16.03.2026",
  },
  {
    id: "17",
    name: "Блузка Chloe",
    brand: "Celine",
    price: 22000,
    currency: "₽",
    description: "Материал шелк",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657393/tg-products/jsaz5u3qrqttlngmnfgv.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657423/tg-products/godbajmqrjcjbz8prrlc.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657426/tg-products/kpizlbff8kyvcowsrsqj.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: [],
    sizes: ["S M L"],
    createdAt: "16.03.2026",
  },
  {
    id: "18",
    name: "Брюки Chanel",
    brand: "Chanel",
    price: 36000,
    currency: "₽",
    description: "Материал шелк и полиэстер",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657428/tg-products/bouempg5bkozzmhbe2xg.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657430/tg-products/u2nmfiipteo7m94vp7vw.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: [],
    sizes: ["S M L"],
    createdAt: "16.03.2026",
  },
  {
    id: "19",
    name: "Шорты Miumiu",
    brand: "Miumiu",
    price: 20000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657432/tg-products/tbxjqmyd3vyze1jgmkvv.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: [],
    sizes: ["S M L"],
    createdAt: "16.03.2026",
  },
  {
    id: "20",
    name: "Лонгслив Miumiu",
    brand: "Miumiu",
    price: 12000,
    currency: "₽",
    description: "Материал хлопок",
    category: "clothing",
    images: ["https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657434/tg-products/petjj0v2jgsvjhxu2t2y.jpg", "https://res.cloudinary.com/dlexrnrhe/image/upload/v1773657436/tg-products/glwgfyzvoxrivzb8bvrc.jpg"],
    specs: [],
    inStock: false,
    madeToOrder: true,
    colors: [],
    sizes: ["S M L"],
    createdAt: "16.03.2026",
  }
];
